#ifndef YOLOV4_TRITON_TENSORRT_VERSION_H
#define YOLOV4_TRITON_TENSORRT_VERSION_H

#define YOLOV4_VERSION_MAJOR 1
#define YOLOV4_VERSION_MINOR 0
#define YOLOV4_VERSION_PATCH 0

#endif //YOLOV4_TRITON_TENSORRT_VERSION_H
